apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-graph
  name: {{ .Values.serviceName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}
    spec:
      containers:
      - args:
        - --max-idle-connections-per-host=32
        lifecycle:
          preStop:
            exec:
              command: # Do not shut the application down immediately
                - "sleep"
                - "10s"
        env:
        - name: SERVICE_NAME
          value: {{ .Values.serviceName }}
        image: {{ .Values.serviceGraphImage }}
        name: mock-service
        ports:
        - containerPort: 8080
        resources: {{ toJson .Values.resources }}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-graph
  name: {{ .Values.serviceName }}
spec:
  ports:
  - name: {{ .Values.httpPortName }}
    port: 8080
  selector:
    app: {{ .Values.serviceName }}

---

apiVersion: v1
data:
  service-graph: |
    services:
    - name: {{ .Values.serviceName }}
      numReplicas: {{ .Values.replicas }}
      responseSize: {{ .Values.responseSize }}
      type: http
kind: ConfigMap
metadata:
  labels:
    app: service-graph
  name: service-graph-config